const express = require("express");
const carController = require("../controllers/CarController.js");
const carRouter = express.Router();
carRouter.get("/", carController.getAll);
carRouter.get("/getOne/:Id", carController.getOne);
carRouter.post("/remove/", carController.remove);
carRouter.post("/update/", carController.update);
carRouter.post("/search", carController.searchCar);
carRouter.post("/add", carController.add);
carRouter.post("/getByCategory", carController.getCarsByCategory);
carRouter.post("/getByMake", carController.getCarsByMake);
carRouter.post("/getByModel", carController.getCarsByModel);
carRouter.post("/getByInterior", carController.getCarsByInterior);
carRouter.post("/getByExterior", carController.getCarsByExterior);
carRouter.post("/getByFueltype", carController.getCarsByFueltype);
carRouter.post("/getBySteering", carController.getCarsBySteering);
carRouter.post("/getByCondition", carController.getCarsByCondition);
carRouter.post("/getByTransmission", carController.getCarsByTransmission);
carRouter.post("/getByBody", carController.getCarsByBody);
carRouter.post("/getByCartype", carController.getCarsByCartype);

module.exports = carRouter;
